# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: ''
    weight: 10

  - name: Publications
    url: 'publications'
    weight: 20

  - name: Members
    url: 'members'
    weight: 30

#  - name: Projects
#    url: '/projects'
#    weight: 50

  - name: Talks&Teaching
    url: 'teaching'
    weight: 60

  - name: Blogs&Books
    url: 'blog'
    weight: 70






#  - name: Contact
#    url: '#contact'
#    weight: 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Curriculum Vitae
#    url: uploads/leonelli_mauro.pdf
#    weight: 50
